name: JEST CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: sergioramos/yarn-actions/install@master
      - name: Run jest test
        run: |
          npm run test
